i: build_i
	./i
build_i: i.cpp
	g++ -std=c++17 -O2 i.cpp -o i

b: build_b
	./b
build_b: b.cpp
	g++ -std=c++17 -O2 b.cpp -o b

c: build_c
	./c
build_c: c.cpp
	g++ -std=c++17 -O2 c.cpp -o c

d: build_d
	./d
build_d: d.cpp
	g++ -std=c++17 -O2 d.cpp -o d
	
m: build_m
	./m
build_m: m.cpp
	g++ -std=c++17 -O2 m.cpp -o m
	
h: build_h
	./h
build_h: h.cpp
	g++ -std=c++17 -O2 h.cpp -o h

j: build_j
	./j
build_j: j.cpp
	g++ -std=c++17 -O2 j.cpp -o j
